import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";

import Header from "@/components/Header";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body className="flex min-h-screen flex-col">
          <Header />
          <Toaster
            position="bottom-right"
            richColors
            expand={true}
            duration={2000}
            visibleToasts={3}
            toastOptions={{
              classNames: {
                toast: "!border-none",
                error: "!bg-red-600 !text-white",
                success: "!bg-green-600 !text-white",
              },
            }}
          />
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
